version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chicpro/ubuntu2004-apache2-php74
    container_name: ubuntu2004-apache2-php74
    ports:
      - "9001:80"
    restart: always
    volumes:
      - ./public:/var/www/html/
      - /tmp/mysql.sock:/var/run/mysqld/mysqld.sock