version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chicpro/apache-php
    container_name: apache-php
    ports:
      - "9001:80"
    restart: always
    volumes:
      - ./public:/var/www/html/
      - /tmp/mysql.sock:/var/run/mysqld/mysqld.sock